services:
  frontend:
    build:
      context: ./Frontend/ProEvent
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - webapi

  webapi:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__Default=workstation id=ProEvent.mssql.somee.com;packet size=4096;user id=Alliina_SQLLogin_1;pwd=uqx3eo6w1r;data source=ProEvent.mssql.somee.com;persist security info=False;initial catalog=ProEvent;TrustServerCertificate=True